# Generated by Django 4.1.3 on 2022-12-14 17:54

import django.core.validators
from django.db import migrations, models
import final_exam_project.core_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('CROSSOVER', 'Crossover'), ('MINIBUS', 'Minibus')], max_length=9)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveIntegerField(validators=[final_exam_project.core_app.validators.ValueInRangeValidator(1980, 2049, message='Year must be between 1980 and 2049')])),
                ('fuel', models.CharField(choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('LPG', 'LPG'), ('ELECTRIC', 'Electric')], max_length=8)),
                ('photo', models.ImageField(upload_to='mediafiles/user_photos/', validators=[final_exam_project.core_app.validators.validate_file_less_than_2mb])),
                ('price_per_day', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
