# Generated by Django 4.1.3 on 2022-12-16 14:27

from django.db import migrations, models
import final_exam_project.core_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='passengers',
            field=models.PositiveIntegerField(default=0, validators=[final_exam_project.core_app.validators.ValueInRangeValidator(1, 6, message='Passengers must be between 1 and 6')]),
            preserve_default=False,
        ),
    ]
